routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/my_page', 'CarController@store')->name('my_page');

Route::resource('cars', 'CarController');

Route::resource('expenses', 'ExpensesController');


Route::get('/select', 'CarController@modelSelect');


Route::resource('models', 'ModelsController');

resources/views/construct.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">



                <p class="p-construct">Šis puslapis greitai bus pasiekiamas....</p>

            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container home-container">
    <div class="row justify-content-center">
        <div class="col-md-8">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
@guest
<div class="my-container">
<span class="text1">Kiek idėdi į automobilį?</span>
            <span class="text2">Paskaičiuok čia!</span>
</div>
@endguest

            @auth

                <div class="my-flex-container">

                            <a href="{{ route('cars.index') }}">
                <div class="cars">
                    <img src="{{ asset('css/img/mycar.png') }}" alt="car">
                    <h3>Mano mašinos</h3>
                </div>
                            </a>
                            <a href="{{ route('expenses.index') }}">
                                <div class="cars">
                                    <img src="{{ asset('css/img/euro.png') }}" alt="car">
                                    <h3>Visos išlaidos</h3>
                                </div>
                            </a>


                </div>
                @endauth
        </div>
    </div>
</div>
@endsection

resources/views/mypage.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                <div class="my-container">
                    mano puslapis
                </div>

            </div>
        </div>
    </div>
@endsection