routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/my_page', 'CarController@store')->name('my_page');

Route::resource('cars', 'CarController');

Route::resource('expenses', 'ExpensesController');


Route::get('/select', 'CarController@modelSelect');


Route::resource('models', 'ModelsController');

app/Http/Controllers/ExpensesController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Car;
use App\Expenses;
use App\Models;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ExpensesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $expenses = DB::table('expenses')->join('cars', function($join)
        {
            $join->on('expenses.cars_id', '=', 'cars.id')->where('cars.user_id', '=',  Auth::user()-> id);
        })->get();
        return view('expenses.index', ['expenses' => $expenses]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cars = DB::table('cars')->join('models', function($join)
        {
            $join->on('cars.models_id', '=', 'models.id')->where('cars.user_id', '=',  Auth::user()-> id);
        })->get();

        return view('expenses.insert',['cars' => $cars]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $expenses = new Expenses();
        $expenses->cars_id = $data['carBrand'];
        $expenses->insurance = $data['insurance'];
        $expenses->fuel = $data['fuel'];
        $expenses->parking = $data['parking'];
        $expenses->repair = $data['repair'];
        $expenses->fine = $data['fine'];
        $expenses->tuning = $data['tuning'];
        $expenses->technical_inspection = $data['ta'];
        $expenses->tires = $data['tires'];
        $expenses->other = $data['other'];
        $expenses->save();
        return  view('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//        $cars_id = Car::where('user_id', '=', $id)->get();
//
//
//        $expenses = Expenses::whereIn ('cars_id', $cars_id)->get();
//
//
//        return  view('expenses.show ',['expenses' => $expenses]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/expenses/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                    <div class="card" style="width: 100%;">
                        <div class="card-header">
                            Išlaidos :
                        </div>

                        <ul class="list-group list-group-flush">
                    @foreach($expenses as $exp)


                                <li class="list-group-item color-item">Išlaidų data: {{ $exp->created_at}}€</li>
                                <li class="list-group-item">Draudimas : {{ $exp->insurance}}€</li>
                                <li class="list-group-item">Kuras : {{ $exp->fuel}}€</li>
                                <li class="list-group-item">Parkavimas: {{ $exp->parking}}€</li>
                                <li class="list-group-item">Remontas: {{ $exp->repair}}€</li>
                                <li class="list-group-item">Baudos: {{ $exp->fine}}€</li>
                                <li class="list-group-item">Tiuningas: {{ $exp->tuning}}€</li>
                                <li class="list-group-item">Techninė apžiūra: {{ $exp->technical_inspection}}€</li>
                                <li class="list-group-item">Padangos: {{ $exp->tires}}€</li>
                                <li class="list-group-item">Kitos išlaidos: {{ $exp->other}}€</li>







                    @endforeach
                        </ul>
                    </div>


            </div>
        </div>
    </div>
@endsection

resources/views/expenses/insert.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <form method="post" action="{{ route('expenses.store') }}">
@csrf

                    <div class="col">
                        <label for="carBrand">Automobilio markė</label>
                        <select class="form-control" name="carBrand" id="carBrand"  required>



                        @foreach($cars as $car)
                            <option value="{{ $car->id }}">{{ $car->name }}</option>
                        @endforeach





                        </select>
                    </div>
                    <h2>Išlaidos:</h2>
<div class="row">

                    <div class="col">
                        <label for="insurance">Draudimas</label>
                        <input type="number" name="insurance" class="form-control" id="insurance" value="0">
                    </div>

                    <div class="col">
                        <label for="fuel">Kuras</label>
                        <input type="number" name="fuel" class="form-control" id="fuel" value="0">
                    </div>

                    <div class="col">
                        <label for="parking">Parkavimas</label>
                        <input type="number" name="parking" class="form-control" id="parking" value="0">
                    </div>
</div>

                    <div class="row">
                    <div class="col">
                        <label for="repair">Remontas</label>
                        <input type="number"name="repair" class="form-control" id="repair" value="0">
                    </div>

                    <div class="col">
                        <label for="fine">Baudos</label>
                        <input type="number" name="fine" class="form-control" id="fine" value="0">
                    </div>


                    <div class="col">
                        <label for="tuning">"Tiuningas"</label>
                        <input type="number" name="tuning" class="form-control" id="tuning" value="0">
                    </div>
                    </div>

                    <div class="row">
                    <div class="col">
                        <label for="ta">T.a.</label>
                        <input type="number" name="ta" class="form-control" id="ta" value="0">
                    </div>

                    <div class="col">
                        <label for="tires">Padangos</label>
                        <input type="number" name="tires" class="form-control" id="tires" value="0">
                    </div>

                    <div class="col">
                        <label for="other">Kitos</label>
                        <input type="number" name="other" class="form-control" id="other" value="0">
                    </div>
                </div>
                    <button type="submit" class="btn btn-primary">submit</button>
                </form>



        </div>
    </div>
@endsection

resources/views/expenses/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif



                        @foreach($expenses as $file)

                        <div class="card" style="width: 18rem;">
                            <div class="card-header">
                                Išlaidos :
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Išlaidų data: {{ $file->created_at}}</li>
                                <li class="list-group-item">Draudimas : {{ $file->insurance}}</li>
                                <li class="list-group-item">Kuras : {{ $file->fuel}}</li>
                                <li class="list-group-item">Parkavimas: {{ $file->parking}}</li>
                                <li class="list-group-item">Remontas: {{ $file->repair}}</li>
                                <li class="list-group-item">Baudos: {{ $file->fine}}</li>
                                <li class="list-group-item">Tiuningas: {{ $file->tuning}}</li>
                                <li class="list-group-item">Techninė apžiūra: {{ $file->technical_inspection}}</li>
                                <li class="list-group-item">Padangos: {{ $file->tires}}</li>
                                <li class="list-group-item">Kitos išlaidos: {{ $file->other}}</li>
                            </ul>
                        </div>


                        @endforeach




            </div>
        </div>
    </div>
@endsection