routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/my_page', 'CarController@store')->name('my_page');

Route::resource('cars', 'CarController');

Route::resource('expenses', 'ExpensesController');


Route::get('/select', 'CarController@modelSelect');


Route::resource('models', 'ModelsController');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public function expensesObject(){
        return $this->hasMany('App\Expenses');
    }

    public function userObject(){
        return $this->belongsTo('App\User');
    }

    public function brandObject(){
        return $this->hasMany('App\Brand');
    }

    public function modelsObject(){
        return $this->hasMany('App\Models');
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Car;
use App\Models;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CarController extends Controller
{
    public function index()
    {
        $cars = DB::table('cars')->join('brands', function($join)
        {
            $join->on('cars.brand_id', '=', 'brands.id')->where('cars.user_id', '=',  Auth::user()-> id);
        })->get();


        return view('cars.index', ['cars' => $cars]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::all();
        $model = Models::all();


       return view('cars.insert',['brand'=>$brands,'model'=>$model]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $cars = new Car();
        $cars->user_id = Auth::user()->id;
        $cars->brand_id = $data['carBrand'][0];
        $cars->manufacture_year = $data['manufactureYear'];
        $cars->purchase_year = $data['purchaseYear'];
        $cars->price = $data['price'];
        $cars->models_id = $data['carModel'][0];
        $cars->save();
        return redirect(route('home'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
















}

resources/views/cars/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif


                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active my-own-color-list-group">
                            Mano mašinos:
                        </a>

                    @foreach($cars as $car)


                            <a href="#" class="list-group-item list-group-item-action">{{ $car -> name }}  {{ $car -> manufacture_year }}m. </a>


                    @endforeach
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/cars/insert.blade.php
@extends('layouts.app')

@section('content')


    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
@auth
                <form method="post" action="{{ route('cars.store') }}">
                    @csrf
                    <meta name="csrf-token" content="{{ csrf_token() }}">



                    <div class="form-group">
                        <label for="carBrand">Automobilio markė</label>
                        <select class="form-control" name="carBrand" id="brand" >

                            <option value="0" disabled = "true" selected = "true">=== Pasirinkite gamintoją ===</option>
                            @foreach($brand as $br)
                                <option value="{{ $br->id }}">{{ $br->name }}</option>
                            @endforeach


                        </select>
                    </div>

                    <div class="form-group">
                        <label for="carModel">Automobilio modelis</label>
                        <select class="form-control" name="carModel" id="model">

                            <option value="0" disabled = "true" selected = "true">=== Pasirinkite modelį ===</option>



                        </select>
                    </div>


                    <div class="form-group">
                        <label for="manufactureYear">Pagaminimo metai</label>
                        <input type="number" class="form-control" name="manufactureYear" id="manufactureYear">
                    </div>

                    <div class="form-group">
                        <label for="purchaseYear">Pirkimo metai</label>
                        <input type="number" class="form-control" name="purchaseYear" id="purchaseYear">
                    </div>

                    <div class="form-group">
                        <label for="price">Pirkimo kaina</label>
                        <input type="number" class="form-control" name="price" id="price">
                    </div>
                    <button type="submit" class="btn btn-primary">submit</button>
                </form>

@endauth

            </div>
        </div>
    </div>





    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>




    <script>
        // alert( 'scriptas pasileido' );

        $(function() {
            $.ajaxSetup({

                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

                }

            });

            $('#brand').on('change', function (e) {
                let id = this.selectedOptions[0].value;
                let carModel = document.getElementById('model');
                $.get(`/carextends/public/models/${id}`, (response) =>{
                    carModel.innerHTML = '<option value="0" disabled = "true" selected = "true">=== Pasirinkite modelį ===</option>';
                    $.each(response, (key, value)=>{

                        var option = document.createElement("option");
                        option.text = value.name;
                        option.value = value.id;
                        carModel.appendChild(option)
                    });
                });
            });
        })

    </script>



























@endsection

resources/views/cars/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container home-container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif


<ul>

@foreach($brand as $br)
    <li>{{ $br->name}} </li>
@endforeach

</ul>

            </div>
        </div>
    </div>
@endsection